language: python
python: 2.7
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=flake8
  - TOX_ENV=coverage
install:
  - pip install tox
  - if [ "x$TOX_ENV" = 'xcoverage' ]; then pip install coveralls --use-mirrors; fi
script:
  - tox -e $TOX_ENV
after_success:
  - if [ "x$TOX_ENV" = 'xcoverage' ]; then coveralls; fi